name: my-rdkit-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rdkit  # from conda-forge

  - pip  # Ensure pip is in the environment
  - streamlit
  - pillow

  - pip:
      - torch  # Let pip install PyTorch
      
